---
# To launch mkdocs use: mkdocs serve
# To launch with debug mode use: mkdocs serve -v
# To build mkdocs use: mkdocs build --clean

# Project information
site_name: PythonBiellaGroup
site_url: https://github.com/PythonBiellaGroup/Bear
site_description: Bear is a Python template system for quick python development.
site_author: PythonBiellaGroup
copyright: Made with ♥ by PBG.

# Repository
repo_url: https://github.com/PythonBiellaGroup/Bear
repo_name: PythonBiellaGroup/Bear
edit_uri: "" #disables edit button

# Configuration
theme:
  name: material
  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  #   include_search_page: false
  #   search_index_only: true
  #
  language: en
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
  #     - search.share
  #     - header.autohide
  #     - content.code.annotate
  #     - navigation.indexes
  #     - navigation.sections
  # - navigation.tabs
  logo: static/images/logo.png
  favicon: static/images/favicon.ico
  font:
    text: Ubuntu
    code: Roboto mono
  palette:
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      dark: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: green
      accent: green
      dark: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - scripts/generate_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [app/src]
          options:
            group_by_category: true
            show_category_heading: true
            show_signature_annotations: true
            line_length: 60
            separate_signature: true
            show_root_toc_entry: false
            merge_init_into_class: true

extra_css:
  - static/css/mkdocstrings.css

# #Extra material theme settings
extra:
  disqus: PythonBiellaGroup
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:pythonbiellagroup@gmail.com
      name: Write to us
    - icon: fontawesome/brands/twitter
      link:
      name: Twitter
    - icon: fontawesome/brands/gitlab
      link:
      name: Gitlab repo
    - icon: fontawesome/brands/linkedin
      link:
      name: Linkedin

markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  # rest of the navigation...
  # defer to gen-files + literate-nav
  - Home: index.md
  - How to use: howto/index.md
  - Code Reference: reference/
  # rest of the navigation...

watch:
  - app
